IRREGULARIDADES = {
    "juros_carencia_sem_datas_claras": {
        "titulo": "Ausência de clara e expressa pactuação das datas de pagamento dos juros de carência",
        "secao": "carencia_fluxo",
        "subtitulo": "Datas de pagamento dos juros de carência",
        "bloco": "irr_juros_carencia_sem_datas_claras",
        "ordem_secao": 10,
        "ordem_item": 10,
    },
    "encadeamento_operacoes": {
        "titulo": "Encadeamento das operações",
        "secao": "carencia_fluxo",
        "subtitulo": "Encadeamento das operações",
        "bloco": "irr_encadeamento_operacoes",
        "ordem_secao": 10,
        "ordem_item": 20,
    },
    "taxa_superior_media_mercado": {
        "titulo": "Onerosidade excessiva: Taxa de Juros Superior às Taxas de Juros Médias de Mercado",
        "secao": "encargos_remuneratorios",
        "subtitulo": "Taxa de juros superior à média de mercado",
        "bloco": "irr_taxa_superior_media_mercado",
        "ordem_secao": 20,
        "ordem_item": 10,
    },
    "juros_superiores_plano_safra": {
        "titulo": "Onerosidade excessiva: Juros remuneratórios superiores à taxa fixada no Plano Safra",
        "secao": "encargos_remuneratorios",
        "subtitulo": "Juros remuneratórios superiores à taxa fixada no Plano Safra",
        "bloco": "irr_juros_superiores_plano_safra",
        "ordem_secao": 20,
        "ordem_item": 20,
    },
    "juros_superiores_12_aa_credito_rural": {
        "titulo": "Juros remuneratórios superiores à taxa de 12,00% a.a. para operações de crédito rural",
        "secao": "encargos_remuneratorios",
        "subtitulo": "Juros remuneratórios superiores a 12,00% a.a.",
        "bloco": "irr_juros_superiores_12_aa_credito_rural",
        "ordem_secao": 20,
        "ordem_item": 30,
    },
    "cdi_com_substituicao_indevida": {
        "titulo": "Ilegalidade e Onerosidade excessiva: Utilização de CDI como encargo remuneratório e substituição indevida pelo Média/INPC/IGP-M (FGV)",
        "secao": "encargos_remuneratorios",
        "subtitulo": "Utilização de CDI com substituição indevida de indexador",
        "bloco": "irr_cdi_com_substituicao_indevida",
        "ordem_secao": 20,
        "ordem_item": 40,
    },
    "cdi_como_encargo_remuneratorio": {
        "titulo": "Ilegalidade e Onerosidade excessiva: Utilização de CDI como encargo remuneratório",
        "secao": "encargos_remuneratorios",
        "subtitulo": "Utilização de CDI como encargo remuneratório",
        "bloco": "irr_cdi_como_encargo_remuneratorio",
        "ordem_secao": 20,
        "ordem_item": 50,
    },
    "taxa_superior_contrato_originario": {
        "titulo": "Onerosidade excessiva: Taxa de juros superior ao contrato originário",
        "secao": "encargos_remuneratorios",
        "subtitulo": "Taxa de juros superior ao contrato originário",
        "bloco": "irr_taxa_superior_contrato_originario",
        "ordem_secao": 20,
        "ordem_item": 60,
    },
    "capitalizacao_sem_pactuacao": {
        "titulo": "Capitalização de juros sem expressa pactuação (anatocismo)",
        "secao": "capitalizacao",
        "subtitulo": "Capitalização de juros sem expressa pactuação",
        "bloco": "irr_capitalizacao_sem_pactuacao",
        "ordem_secao": 30,
        "ordem_item": 10,
    },
    "periodicidade_capitalizacao_rural": {
        "titulo": "Periodicidade da capitalização para contratos rurais e anatocismo",
        "secao": "capitalizacao",
        "subtitulo": "Periodicidade da capitalização em contratos rurais",
        "bloco": "irr_periodicidade_capitalizacao_rural",
        "ordem_secao": 30,
        "ordem_item": 20,
    },
    "capitalizacao_anual_sem_pactuacao": {
        "titulo": "Capitalização de juros com periodicidade anual sem expressa pactuação",
        "secao": "capitalizacao",
        "subtitulo": "Capitalização anual sem expressa pactuação",
        "bloco": "irr_capitalizacao_anual_sem_pactuacao",
        "ordem_secao": 30,
        "ordem_item": 30,
    },
    "cobranca_indevida_seguros_tarifa": {
        "titulo": "Cobrança indevida de Seguros e Tarifa",
        "secao": "cobrancas_acessorias",
        "subtitulo": "Cobrança indevida de seguros e tarifa",
        "bloco": "irr_cobranca_indevida_seguros_tarifa",
        "ordem_secao": 40,
        "ordem_item": 10,
    },
    "inadimplemento_ilegal_oneroso": {
        "titulo": "Encargos de inadimplemento - Ilegalidade e Onerosidade excessiva",
        "secao": "inadimplemento",
        "subtitulo": "Encargos de inadimplemento",
        "bloco": "irr_inadimplemento_ilegal_oneroso",
        "ordem_secao": 50,
        "ordem_item": 10,
    },
}

